// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
)

type Employee struct {
	Guid        string         `json:"guid"`
	EmployeeID  sql.NullInt32  `json:"employee_id"`
	Fullname    sql.NullString `json:"fullname"`
	Email       string         `json:"email"`
	PhoneNumber sql.NullString `json:"phone_number"`
	DateOfBirth sql.NullTime   `json:"date_of_birth"`
	Status      string         `json:"status"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	CreatedBy   string         `json:"created_by"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	UpdatedBy   sql.NullString `json:"updated_by"`
}
